service:
  name: passbook
environment: local

server:
  port: 8080

mongo-db:
  name: entertainment

security:
  jwt:
    secret-key: 2D4A614E645267556B58703273357638792F423F4428472B4B6250655368566D
    token:
      ttl: 60

spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}

  mvc:
    dispatch-options-request: true # ✅ Allows handling of OPTIONS requests
