service:
  name: passbook
environment: local

server:
  port: 8080

mongo-db:
  name: entertainment

security:
  jwt:
    secret-key:
    token:
      ttl: 60

spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
