service:
  name: passbook
environment: local

server:
  port: 8080

mongo-db:
  name: entertainment

security:
  jwt:
    secret-key:
    token:
      ttl: 60

spring:
  data:
    mongodb:
      uri: mongodb+srv://ravibala-13:Bals2202@fitncluster.uck1z.mongodb.net/FitNSport?retryWrites=true&w=majority